export const config = {
  settable: '__',
  apiRoot: 'https://api.github.com',
};

export const users = [
  'adrianmg',
  'ampinsk',
  'ashygee',
  'auareyou',
  'benbalter',
  'binarymuse',
  'brianlovin',
  'broccolini',
  'bruce',
  'califa',
  'cheshire137',
  'colebemis',
  'colinkeany',
  'dmleong',
  'donokuda',
  'eliperkins',
  'elisealix22',
  'emilybrick',
  'iron-ham',
  'jasonlong',
  'jonrohan',
  'joshaber',
  'katmeister',
  'lindseyb',
  'mamuso',
  'matthewferry',
  'max',
  'mxstbr',
  'nplasterer',
  'ohjoycelau',
  'pmarsceill',
  'rnystrom',
  'shawnbot',
  'sophshep',
  'superbryntendo',
  'teenage-witch',
  'thedamianhdez',
  'vdepizzol',
  'zaralogue',
];

export const orgs = [
  'github',
  'withspectrum',
  'facebook',
  'figma',
  'zeit',
  'apollographql',
  'atom',
  'meteor',
  'mongodb',
  'narative',
  'apple',
  'microsoft',
  'netlify',
  'unifiedjs',
  'rehooks',
  'emberjs',
  'styled-components',
  'tc39',
  'hackclub',
  'mozilla-mobile',
  'ant-design',
  'prisma',
  'yarnpkg',
  'open-wc',
  'popperjs',
  'vlang',
  'bbc',
  'puppeteer',
  'efforg',
  'mozilla',
  'adobe',
  'textmate',
  'neovim',
  'overleaf',
  'komodo',
  'railsgirls',
  'freecodecamp',
];

export const repos = [
  'withspectrum/spectrum',
  'vlang/v',
  'apollographql/react-apollo',
  'outline/outline',
  'emotion-js/emotion',
  'specfm/design-details',
  'styled-components/styled-components',
  'zeit/hyper',
  'prisma/nexus',
  'craigkerstiens/postgresguide.com',
  'davidecalignano/MediumLightbox',
  'microsoft/tsdoc',
  'ziishaned/learn-regex',
];

export const issuesRepos = ['withspectrum/spectrum', 'facebook/react', 'microsoft/vscode'];

export const pullsRepos = ['withspectrum/spectrum', 'facebook/react', 'microsoft/vscode'];

export const apps = [
  'stale',
  'github-learning-lab',
  'app-center',
  'azure-boards',
  'azure-pipelines',
  'codecov',
  'travis-ci',
  'instabug',
  'percy',
  'devhub-app',
  'issue-label-bot',
  'rollbar',
  'logrocket',
];
